### ISSUE TITLE
test network & containers get left behind on build failure

### ISSUE THREAD

**Issue by unclejack** [contiv/auth_proxy#136]
My changes couldn't be compiled. The test setup started by `make test` got left behind on my Docker daemon. I had to remove the containers and the Docker network to get rid of them.

Perhaps we could do something to ensure we only spin up the test environment after we're sure we can run the auth_proxy:devbuild image?

**Comment by dseevr** [comment]
I think the ideal solution here is to ensure that _one_ build happens before any tests, whether you run `make ci`, `make tests`, `make unit-tests`, or `make systemtests`

The only reason we don't have build as a pre-req for those targets is because it added a ton of unnecessary time to the targets which were supersets of other targets.

Is there a quick and clean solution for that?  Maybe just a variable to track whether a build has happened in the Makefile?
